import pygame
pygame.init()
pygame.mixer.init()
pygame.mixer.music.load("../data/audio/ok-i-pull-up-shorted.mp3")
pygame.mixer.music.play(-1)
pygame.mixer.music.stop()
pygame.mixer.music.play(-1)
pygame.mixer.music.pause()
pygame.time.delay(500)
pygame.mixer.music.unpause()
print("get_pos:", pygame.mixer.music.get_pos())
pygame.time.delay(500)
print("get_pos:", pygame.mixer.music.get_pos())
